---
title: "MCF10a degron timecourse DEA figures"
author: "Haley Greenyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(EnhancedVolcano)
library(ggvenn)
library(VennDiagram)
library(limma)


library(readr)
library(openxlsx)

library(ggplot2)
library(UpSetR)
library(pheatmap)
library(ComplexHeatmap)

source("/slipstream_old/home/hgreenyer/Rscripts/RNAseq_DEA_functions.R")
```
# title goes here
## smaller title 
regular text 
```{r directories, include=FALSE}

RNAseq_in_dir <- '/slipstream_old/home/hgreenyer/PROJECTS/MCF10A_RUNX1_TIMECOURSE_2023/MCF10A_TimeCourse_RNAseq/DEA_output/'

out_dir <- '/slipstream_old/home/hgreenyer/PROJECTS/MCF10A_RUNX1_TIMECOURSE_2023/MCF10A_TimeCourse_RNAseq/DEA_output/'
out_dir_fig <- '/slipstream_old/home/hgreenyer/PROJECTS/MCF10A_RUNX1_TIMECOURSE_2023/MCF10A_TimeCourse_RNAseq/Figures/'

```

```{r load timecourse DEGs, message=FALSE, warning=FALSE, include=FALSE}

#load full normalized counts 
full_normCounts <- read_csv(paste(RNAseq_in_dir,'MCF10A_RUNX1_TimeCourse_all_NormCounts.csv', sep = ''))

row.names(full_normCounts) <- full_normCounts$input

#load DESeq results for each time point 
deg_3H_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_3H_DESeqRes.csv', sep = ''))

deg_6H_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_6H_DESeqRes.csv', sep = ''))

deg_12H_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_12H_DESeqRes.csv', sep = ''))

deg_24H_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_24H_DESeqRes.csv', sep = ''))

deg_48H_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_48H_DESeqRes.csv', sep = ''))

deg_6D_full <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_6D_DESeqRes.csv', sep = ''))


#load filtered DESeq results 
deg_3H <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_3H_DEGs.csv', sep = ''))

deg_6H <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_6H_DEGs.csv', sep = ''))

deg_12H <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_12H_DEGs.csv', sep = ''))

deg_24H <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_24H_DEGs.csv', sep = ''))

deg_48H <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_48H_DEGs.csv', sep = ''))

deg_6D <- read_csv(paste(RNAseq_in_dir,'MCF10a_C7_DMSOvDTAG_6D_DEGs.csv', sep = ''))



```

```{r sample correlation}

sample_cor <- cor(as.matrix(full_normCounts[,9:ncol(full_normCounts)]))
heatmap(sample_cor)
```


```{r split RNAseq DEGs, include = FALSE}

#extract up and down-regulated genes from DESeq results 
#RNAseq 
up_3h <- subset(deg_3H, deg_3H$log2FoldChange > 0)
dwn_3h <- subset(deg_3H, deg_3H$log2FoldChange < 0)

up_6h <- subset(deg_6H, deg_6H$log2FoldChange > 0)
dwn_6h <- subset(deg_6H, deg_6H$log2FoldChange < 0)

up_12h <- subset(deg_12H, deg_12H$log2FoldChange > 0)
dwn_12h <- subset(deg_12H, deg_12H$log2FoldChange < 0)

up_24h <- subset(deg_24H, deg_24H$log2FoldChange > 0)
dwn_24h <- subset(deg_24H, deg_24H$log2FoldChange < 0)

up_48h <- subset(deg_48H, deg_48H$log2FoldChange > 0)
dwn_48h <- subset(deg_48H, deg_48H$log2FoldChange < 0)

up_6D <- subset(deg_6D, deg_6D$log2FoldChange > 0)
dwn_6D <- subset(deg_6D, deg_6D$log2FoldChange < 0)


```

# MCF10a Degron Time Course Volcano Plots 
```{r DE volcano volcano plots, echo=FALSE}

#get top 10% fold change cutoffs 
FC_3H <- quantile(abs(deg_3H_full$log2FoldChange), probs=0.75, na.rm=TRUE)
FC_6H <- quantile(abs(deg_6H_full$log2FoldChange), probs=0.75, na.rm=TRUE)
FC_12H <- quantile(abs(deg_12H_full$log2FoldChange), probs=0.75, na.rm=TRUE)
FC_24H <- quantile(abs(deg_24H_full$log2FoldChange), probs=0.75, na.rm=TRUE)
FC_48H <- quantile(abs(deg_48H_full$log2FoldChange), probs=0.75, na.rm=TRUE)
FC_6D <- quantile(abs(deg_6D_full$log2FoldChange), probs=0.75,na.rm=TRUE)


#get top 10% pvales 
P_3H <- quantile(deg_3H_full$pvalue, probs=0.001, na.rm=TRUE)
P_6H <- quantile(deg_6H_full$pvalue, probs=0.001, na.rm=TRUE)
P_12H <- quantile(deg_12H_full$pvalue, probs=0.001, na.rm=TRUE)
P_24H <- quantile(deg_24H_full$pvalue, probs=0.001, na.rm=TRUE)
P_48H <- quantile(deg_48H_full$pvalue, probs=0.001, na.rm=TRUE)
P_6D <- quantile(deg_6D_full$pvalue, probs=0.001,na.rm=TRUE)


top_3H <- deg_3H_full[which(abs(deg_3H_full$log2FoldChange) >= FC_3H & deg_3H_full$pvalue <= P_3H),]
top_6H <- deg_3H_full[which(abs(deg_6H_full$log2FoldChange) >= FC_3H & deg_6H_full$pvalue <= P_6H),]
top_12H <- deg_3H_full[which(abs(deg_12H_full$log2FoldChange) >= FC_3H & deg_12H_full$pvalue <= P_12H),]
top_24H <- deg_24H_full[which(abs(deg_24H_full$log2FoldChange) >= FC_24H & deg_24H_full$pvalue <= P_24H),]
top_48H <- deg_48H_full[which(abs(deg_48H_full$log2FoldChange) >= FC_48H & deg_48H_full$pvalue <= P_48H),]
top_6D <- deg_6D_full[which(abs(deg_6D_full$log2FoldChange) >= FC_6D & deg_6D_full$pvalue <= P_6D),]


#filter labels
top_3H <- top_3H[!(top_3H$name == 'None'),]
top_6H <- top_6H[!(top_6H$name == 'None'),]
top_12H <- top_12H[!(top_12H$name == 'None'),]
top_24H <- top_24H[!(top_24H$name == 'None'),]
top_48H <- top_48H[!(top_48H$name == 'None'),]
top_6D <- top_6D[!(top_6D$name == 'None'),]


#RNAseq 3H
EnhancedVolcano(deg_3H_full, lab=deg_3H_full$name, selectLab = top_3H$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 3H', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-2.5,2.5))  

#RNAseq 6H
EnhancedVolcano(deg_6H_full, lab=deg_6H_full$name, selectLab = top_6H$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 6H', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-2.5,2.5))  

#RNAseq 12H
EnhancedVolcano(deg_12H_full, lab=deg_12H_full$name, selectLab = top_12H$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 12H', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-2.5,2.5))  

#RNAseq 24H
EnhancedVolcano(deg_24H_full, lab=deg_24H_full$name, selectLab = top_24H$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 24H', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-10,10))  

#RNAseq 48H
EnhancedVolcano(deg_48H_full, lab=deg_48H_full$name, selectLab = top_48H$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 48H', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-7,7)) 

#RNAseq 6D
EnhancedVolcano(deg_6D_full, lab=deg_6D_full$name, selectLab = top_6D$name, x='log2FoldChange', y='pvalue',title = 'RNAseq ASYNC 6D', subtitle = 'MCF10a DMSO vs dTAG',axisLabSize = 8, pCutoff = 0.05, FCcutoff = 1, labSize = 2, titleLabSize = 12, subtitleLabSize = 10, legendLabSize = 8, legendIconSize = 4, captionLabSize = 8, xlim = c(-10,10))



```

```{r DEG barplots, echo=FALSE}
#get counts of up and downregulated genes across phase conditions
timepoint <- c(rep('3H',2),rep('6H',2),rep('12H',2),rep('24H',2), rep('48H',2), rep('6D',2))
de <- rep(c('UP','DOWN'),6)
value <- c(nrow(up_3h),nrow(dwn_3h),nrow(up_6h),nrow(dwn_6h),nrow(up_12h),nrow(dwn_12h),nrow(up_24h),nrow(dwn_24h),nrow(up_48h),nrow(dwn_48h),nrow(up_6D),nrow(dwn_6D))
  
DEA_count_df <- data.frame(timepoint,de,'value'=value)

#convert to factor to prevent alphabetic order 
DEA_count_df$timepoint <- factor(DEA_count_df$timepoint, levels = unique(DEA_count_df$timepoint))

#barplot of up and down regulated gene counts at each time point 
ggplot(DEA_count_df, aes(fill=de, y=value, x=timepoint, label=value)) + geom_bar(position = 'dodge', stat='identity') + labs(title ='MCF10a RUNX1 Degron Time Course RNA-seq DEGs', y='counts', fill='Expression') + scale_fill_manual(values=c('#285fb5','#f24e4e')) + xlab('Timepoint') + ylab('')


```

```{r DEG lists, include=FALSE}

#get lists of DEGs

upreg_list <- list('3H' = up_3h$Gene,'6H' = up_6h$Gene,'12H' = up_12h$Gene,'24H' = up_24h$Gene,'48H' = up_48h$Gene, '6D' = up_6D$Gene)

downreg_list <- list('3H' = dwn_3h$Gene,'6H' = dwn_6h$Gene,'12H' = dwn_12h$Gene,'24H' = dwn_24h$Gene,'48H' = dwn_48h$Gene, '6D' = dwn_6D$Gene)

all_list <- list('3H' = deg_3H$Gene,'24H' = deg_24H$Gene,'48H' = deg_48H$Gene, '6D' = deg_6D$Gene)

```

```{r DEG upset plots, echo=FALSE}
#SKIP RUN 
#upset plots 
m_up = make_comb_mat(upreg_list)
m_dwn = make_comb_mat(downreg_list)
#m_all = make_comb_mat(all_list)


UpSet(m_up, comb_col = c('red','blue','black')[comb_degree(m_up)],top_annotation = upset_top_annotation(m_up, add_numbers = TRUE), right_annotation = upset_right_annotation(m_up, add_numbers = TRUE),height = unit(3.5, "cm"), width = unit(10,"cm"),comb_order = order(comb_size(m_up)))

UpSet(m_dwn, comb_col = c('red','blue','black')[comb_degree(m_dwn)],top_annotation = upset_top_annotation(m_dwn, add_numbers = TRUE), right_annotation = upset_right_annotation(m_dwn, add_numbers = TRUE),height = unit(3.5, "cm"), width = unit(10,"cm"), comb_order = order(comb_size(m_dwn)))

#UpSet(m_all, comb_col = c('red','blue','black')[comb_degree(m_all)],top_annotation = upset_top_annotation(m_all, add_numbers = TRUE), right_annotation = upset_right_annotation(m_all, add_numbers = TRUE),height = unit(3.5, "cm"), width = unit(10,"cm"), comb_order = order(comb_size(m_all)))
```

```{r DEG venn diagrams, echo=FALSE}
#DONT RUN
#too many timepoints for this right now 
ggvenn::ggvenn(upreg_list, fill_color = c("#8dd3c7", "#ffffb3", "#bebada","#fb8072", "#80b1d3"), stroke_size = 0.5, set_name_size = 5)
ggvenn::ggvenn(downreg_list, fill_color = c("#8dd3c7", "#ffffb3", "#bebada","#fb8072", "#80b1d3"), stroke_size = 0.5, set_name_size = 5)

```

```{r export venn overlaps, include = FALSE}

export_olaps(upreg_list, out_pref = 'MCF10a_C7_TimeCourse_RNAseq_upRegDEG', out_dir = out_dir)
export_olaps(downreg_list, out_pref = 'MCF10a_C7_TimeCourse_RNAseq_dwnRegDEG', out_dir = out_dir)

```


# Heatmaps
```{r RNAseq heatmap annotation}

#subset normcounts for 48H and 6D 
nc_heat <- full_normCounts %>% dplyr::select(contains('input') | contains('C7') | contains('_48H') | contains('_6D')) %>% na.omit()

all_degs <- unique(c(deg_3H$Gene, deg_48H$Gene, deg_6D$Gene))

#extract only DEGs across any timepoint 
nc_heat <- subset(nc_heat, nc_heat$input %in% all_degs)

#format
nc_heat_m <- nc_heat[,-1]
rownames(nc_heat_m) <- nc_heat$input


#annotation for the heatmap 
timepoint <- c(rep('3H',6), rep('48H',6), rep('6D',6))
condition <- c(rep(c(rep('DMSO',3),rep('DTAG',3)), 3))
replicate <- c(rep(c('rep1','rep2','rep3'),6))
  
df_P <- data.frame(timepoint,condition,replicate)
row.names(df_P) <- names(nc_heat_m)

#condensed data averaged across replicates 
nc_heat_avg <- as.data.frame(matrix(ncol=7, nrow=nrow(nc_heat)))
names(nc_heat_avg) <- c('input','MCF10a_3H_DMSO','MCF10a_3H_DTAG','MCF10a_48H_DMSO','MCF10a_48H_DTAG','MCF10a_6D_DMSO','MCF10a_6D_DTAG')

nc_heat_avg$input <- nc_heat$input 
nc_heat_avg$MCF10a_3H_DMSO <- rowMeans(nc_heat[,c(2,4)])
nc_heat_avg$MCF10a_3H_DTAG <- rowMeans(nc_heat[,c(5:7)])
nc_heat_avg$MCF10a_48H_DMSO <- rowMeans(nc_heat[,c(8:10)])
nc_heat_avg$MCF10a_48H_DTAG <- rowMeans(nc_heat[,c(11:13)])
nc_heat_avg$MCF10a_6D_DMSO <- rowMeans(nc_heat[,c(14,16)])
nc_heat_avg$MCF10a_6D_DTAG <- rowMeans(nc_heat[,c(17:19)])

#format
nc_heat_avg_m <- nc_heat_avg[,-1]
rownames(nc_heat_avg_m) <- nc_heat_avg$input


#annotation for the heatmap 
Time <- c(rep('3H',2), rep('48H',2), rep('6D',2))
Treatment <- c(rep(c('DMSO','DTAG'), 3))
  
df_P_avg <- data.frame(Time,Treatment)
row.names(df_P_avg) <- names(nc_heat_avg_m)

```

```{r heatmap}

#heatmap with all replicates included 

#pheatmap(as.matrix(nc_heat_m[,]), show_colnames = FALSE,show_rownames = FALSE, scale='row', cluster_cols = FALSE, treeheight_row = 0)

col_labs <- c('3H DMSO','3H DTAG','48H DMSO','48H DTAG','6D DMSO','6D DATG')
pheatmap(as.matrix(nc_heat_avg_m[,]), labels_col = col_labs,show_colnames = FALSE,show_rownames = FALSE, scale='row', cluster_cols = FALSE, treeheight_row = 0, annotation_col = df_P_avg)

#heatmap averaged across replicates 

```


```{r load pathways}

all_gene_sets <- msigdbr(species = "Homo sapiens", category = 'H')
msigdbr_t2g = all_gene_sets %>% dplyr::distinct(gs_name, gene_symbol) %>% as.data.frame()

```


```{r pathway analysis dataset}
get_pathways <- function(deg_df, gene_sets, t2g){
  #filter db 
  db_genes <- subset(gene_sets, gene_sets$human_ensembl_gene %in% deg_df$Gene)
  
  #cluster profielr 
  enrich_res <- enricher(gene = unique(deg_df$name), TERM2GENE = t2g, pvalueCutoff = 0.05)
  
  #plots
  #show(barplot(enrich_res, showCategory = 10))
  #mutate(enrich_res, qscore = -log(p.adjust, base=10)) %>%
    #barplot(x="qscore", showCategory = 10)

  show(dotplot(enrich_res, showCategory=10))
}

#not enough genes in either of the 3H up/down alone 
get_pathways(deg_3H, all_gene_sets, msigdbr_t2g)



#not enough genes in the up 48h?
#get_pathways(up_48h, all_gene_sets, msigdbr_t2g)
get_pathways(deg_48H, all_gene_sets, msigdbr_t2g)

get_pathways(up_6D, all_gene_sets, msigdbr_t2g)
get_pathways(dwn_6D, all_gene_sets, msigdbr_t2g)

setwd("~/")
```

```{r pathway stuff}

library()


```






